build:
	@spm build

deploy:
	@rm -rf ../../sea-modules/shadow/leagueoffruits
	@mkdir  ../../sea-modules/shadow/leagueoffruits
	@mkdir  ../../sea-modules/shadow/leagueoffruits/1.0.0
	@cp     dist/* ../../sea-modules/shadow/leagueoffruits/1.0.0
	@echo
	@echo   " deploy to seajs-modules/shadow/leagueoffruits/1.0.0"
	@echo
