build:
	@spm build

deploy:
	@rm -rf ../../sea-modules/mopvhs/backstretch
	@mkdir  ../../sea-modules/mopvhs/backstretch
	@mkdir  ../../sea-modules/mopvhs/backstretch/2.0.4
	@cp     dist/* ../../sea-modules/mopvhs/backstretch/2.0.4
	@echo
	@echo   " deploy to seajs-modules/mopvhs/backstretch/2.0.4"
	@echo
